# edX community translations have been downloaded from Japanese (Japan) (http://www.transifex.com/open-edx/edx-platform/language/ja_JP/).
# Copyright (C) 2020 EdX
# This file is distributed under the GNU AFFERO GENERAL PUBLIC LICENSE.
#
# Translators:
# わたカフェの店長, 2014,2017
# kawa <h.kawasaki@nttks.co.jp>, 2014
# h_yoshida <h_yoshida@matsumo-sys.com>, 2014-2015
# Juan Camilo Montoya Franco <juan.montoya@edunext.co>, 2017
# Kyoto University <edxkyotoux@gmail.com>, 2017
# sunk <s.kim@nttks.co.jp>, 2014
# Takashi Nagai <ngi644@gmail.com>, 2014
# Toshiboumi Ohta <ohta@securesky-tech.com>, 2015,2017-2018
# Shige Usui <ushige@live.com>, 2014
# わたカフェの店長, 2013
msgid ""
msgstr ""
"Project-Id-Version: edx-platform\n"
"Report-Msgid-Bugs-To: openedx-translation@googlegroups.com\n"
"POT-Creation-Date: 2020-08-23 20:42+0000\n"
"PO-Revision-Date: 2020-07-19 20:45+0000\n"
"Last-Translator: edx_transifex_bot <i18n-working-group+edx-transifex-bot@edx.org>\n"
"Language-Team: Japanese (Japan) (http://www.transifex.com/open-edx/edx-platform/language/ja_JP/)\n"
"Language: ja_JP\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: cms/djangoapps/api/v1/serializers/course_runs.py:52
msgid "Course team user does not exist"
msgstr ""

#: cms/djangoapps/contentstore/course_group_config.py:27
msgid ""
"The groups in this configuration can be mapped to cohorts in the Instructor "
"Dashboard."
msgstr "この設定内のグループは講師用ダッシュボード内のコホートにマッピングできます。"

#: cms/djangoapps/contentstore/course_group_config.py:30
msgid "Content Groups"
msgstr "コンテンツグループ"

#: cms/djangoapps/contentstore/course_group_config.py:65
#: cms/djangoapps/contentstore/views/certificates.py:142
msgid "invalid JSON"
msgstr "無効なJSON"

#: cms/djangoapps/contentstore/course_group_config.py:74
msgid "must have name of the configuration"
msgstr "この設定の名前を決めてください"

#: cms/djangoapps/contentstore/course_group_config.py:76
msgid "must have at least one group"
msgstr "最低１つグループが必要です"

#: cms/djangoapps/contentstore/course_group_config.py:114
msgid "unable to load this type of group configuration"
msgstr ""

#: cms/djangoapps/contentstore/course_info_model.py:73
#: cms/djangoapps/contentstore/course_info_model.py:148
msgid "Invalid course update id."
msgstr "無効な講座更新ID。"

#: cms/djangoapps/contentstore/course_info_model.py:115
msgid "Course update not found."
msgstr "講座更新がありません。"

#: cms/djangoapps/contentstore/courseware_index.py:246
msgid "Could not index item: {}"
msgstr "項目の見出しを作成できませんでした: {}"

#: cms/djangoapps/contentstore/courseware_index.py:268
msgid "General indexing error occurred"
msgstr "見出し作成エラーが発生しました"

#: cms/djangoapps/contentstore/courseware_index.py:352
msgid "(Unnamed)"
msgstr "(名称未設定)"

#: cms/djangoapps/contentstore/git_export_utils.py:39
#, python-brace-format
msgid ""
"GIT_REPO_EXPORT_DIR not set or path {0} doesn't exist, please create it, or "
"configure a different path with GIT_REPO_EXPORT_DIR"
msgstr ""
"GIT_REPO_EXPORT_DIR が設定されていないか、パス {0} が存在しません。作成するか、GIT_REPO_EXPORT_DIR "
"に違うパスを設定してください"

#: cms/djangoapps/contentstore/git_export_utils.py:42
msgid ""
"Non writable git url provided. Expecting something like: "
"git@github.com:edx/edx4edx_lite.git"
msgstr ""

#: cms/djangoapps/contentstore/git_export_utils.py:44
msgid ""
"If using http urls, you must provide the username and password in the url. "
"Similar to https://user:pass@github.com/user/course."
msgstr ""
"httpのURLを使用している場合、ユーザー名とパスワードをURLに含めてください。https://user:pass@github.com/user/course"
" のような形式です。"

#: cms/djangoapps/contentstore/git_export_utils.py:47
msgid "Unable to determine branch, repo in detached HEAD mode"
msgstr "detached HEAD状態のレポジトリではブランチを決定できません"

#: cms/djangoapps/contentstore/git_export_utils.py:48
msgid "Unable to update or clone git repository."
msgstr "gitレポジトリの更新または複製ができません。"

#: cms/djangoapps/contentstore/git_export_utils.py:49
msgid "Unable to export course to xml."
msgstr "コースをxmlへエクスポートすることができません。"

#: cms/djangoapps/contentstore/git_export_utils.py:50
msgid "Unable to configure git username and password"
msgstr "gitのユーザー名とパスワードを設定することができません"

#: cms/djangoapps/contentstore/git_export_utils.py:51
msgid ""
"Unable to commit changes. This is usually because there are no changes to be"
" committed"
msgstr "変更をコミットすることができません。通常コミットする変更が無い場合です"

#: cms/djangoapps/contentstore/git_export_utils.py:53
msgid ""
"Unable to push changes.  This is usually because the remote repository "
"cannot be contacted"
msgstr "変更をプッシュすることができません。通常リモートレポジトリに接続できない場合です"

#: cms/djangoapps/contentstore/git_export_utils.py:55
msgid "Bad course location provided"
msgstr "間違ったコースロケーションです"

#: cms/djangoapps/contentstore/git_export_utils.py:56
msgid "Missing branch on fresh clone"
msgstr "新規クローンにブランチがありません"

#: cms/djangoapps/contentstore/management/commands/git_export.py:35
msgid ""
"Take the specified course and attempt to export it to a git repository\n"
". Course directory must already be a git repository. Usage:  git_export <course_loc> <git_url>"
msgstr ""
"gitレポジトリにエクスポートするコースを選んで実行してください。\n"
"コースディレクトリはgitレポジトリである必要があります。使用方法: git_export <course_loc> <git_url>"

#: cms/djangoapps/contentstore/tasks.py:247
#: cms/djangoapps/contentstore/tasks.py:378
#, python-brace-format
msgid "Unknown User ID: {0}"
msgstr "不明のユーザーID: {0}"

#: cms/djangoapps/contentstore/tasks.py:251
#: cms/djangoapps/contentstore/tasks.py:382
msgid "Permission denied"
msgstr "権限拒否"

#: cms/djangoapps/contentstore/tasks.py:406
#: cms/djangoapps/contentstore/views/import_export.py:134
msgid "We only support uploading a .tar.gz file."
msgstr ".tar.gzファイルのアップロードのみサポートされています。"

#: cms/djangoapps/contentstore/tasks.py:419
msgid "Tar file not found"
msgstr "tarファイルが見つかりません"

#: cms/djangoapps/contentstore/tasks.py:465
msgid "Unsafe tar file. Aborting import."
msgstr "安全ではないtarファイルです。インポートを中止します。"

#: cms/djangoapps/contentstore/tasks.py:498
#, python-brace-format
msgid "Could not find the {0} file in the package."
msgstr "パッケージ内にファイル{0}が見つかりませんでした。"

#: cms/djangoapps/contentstore/utils.py:440
msgid "Deleted Group"
msgstr "削除されたグループ"

#. Translators: This is building up a list of groups. It is marked for
#. translation because of the
#. comma, which is used as a separator between each group.
#: cms/djangoapps/contentstore/utils.py:505
#, python-brace-format
msgid "{previous_groups}, {current_group}"
msgstr "{previous_groups}、{current_group}"

#: cms/djangoapps/contentstore/video_utils.py:44
msgid "The image must have name, content type, and size information."
msgstr "画像には名前、コンテンツの種類、サイズの情報が必要です。"

#: cms/djangoapps/contentstore/video_utils.py:46
#, python-brace-format
msgid ""
"This image file type is not supported. Supported file types are "
"{supported_file_formats}."
msgstr "この画像ファイルの種類はサポートされていません。対応ファイルの種類は {supported_file_formats} です。"

#: cms/djangoapps/contentstore/video_utils.py:50
#, python-brace-format
msgid "This image file must be smaller than {image_max_size}."
msgstr "この画像ファイルサイズは {image_max_size} を超えてはいけません。"

#: cms/djangoapps/contentstore/video_utils.py:54
#, python-brace-format
msgid "This image file must be larger than {image_min_size}."
msgstr "この画像ファイルサイズは{image_min_size} 以上でなければなりません。。"

#: cms/djangoapps/contentstore/video_utils.py:61
#: cms/djangoapps/contentstore/video_utils.py:63
msgid ""
"There is a problem with this image file. Try to upload a different file."
msgstr "この画像ファイルには問題があります。別のファイルをアップロードしてください。"

#: cms/djangoapps/contentstore/video_utils.py:66
#, python-brace-format
msgid ""
"Recommended image resolution is "
"{image_file_max_width}x{image_file_max_height}. The minimum resolution is "
"{image_file_min_width}x{image_file_min_height}."
msgstr ""
"推奨される画像解像度は{image_file_max_width}x{image_file_max_height}です。最小解像度は{image_file_min_width}x{image_file_min_height}です。"

#: cms/djangoapps/contentstore/video_utils.py:74
#, python-brace-format
msgid ""
"This image file must have an aspect ratio of "
"{video_image_aspect_ratio_text}."
msgstr "この画像ファイルの縦横比は{video_image_aspect_ratio_text}でなければなりません。 "

#: cms/djangoapps/contentstore/video_utils.py:81
msgid ""
"The image file name can only contain letters, numbers, hyphens (-), and "
"underscores (_)."
msgstr "画像ファイル名に含められるのは文字、数字、記号 (-) および (_) のみです。"

#: cms/djangoapps/contentstore/views/assets.py:431
msgid "Upload completed"
msgstr "アップロード完了"

#: cms/djangoapps/contentstore/views/assets.py:475
#, python-brace-format
msgid ""
"File {filename} exceeds maximum size of {maximum_size_in_megabytes} MB."
msgstr ""

#: cms/djangoapps/contentstore/views/certificates.py:165
msgid "must have name of the certificate"
msgstr "修了証名を決めてください"

#: cms/djangoapps/contentstore/views/certificates.py:250
#, python-brace-format
msgid "Certificate dict {0} missing value key '{1}'"
msgstr "修了証ディクショナリ {0} のキー値 '{1}' がありません"

#: cms/djangoapps/contentstore/views/certificates.py:355
#: cms/djangoapps/contentstore/views/certificates.py:393
#, python-brace-format
msgid "PermissionDenied: Failed in authenticating {user}"
msgstr "権限が拒否されました: {user} の認証失敗"

#: cms/djangoapps/contentstore/views/component.py:255
#, python-brace-format
msgid "{platform_name} Support Levels:"
msgstr "{platform_name}のサポートレベル: "

#: cms/djangoapps/contentstore/views/component.py:260
msgid "HTML"
msgstr "HTML"

#: cms/djangoapps/contentstore/views/component.py:261
msgid "Problem"
msgstr ""

#: cms/djangoapps/contentstore/views/component.py:262
msgid "Video"
msgstr "動画"

#: cms/djangoapps/contentstore/views/component.py:290
msgid "Blank"
msgstr "空欄"

#: cms/djangoapps/contentstore/views/course.py:340
msgid "Course has been successfully reindexed."
msgstr "講座の見出し再作成が完了しました。"

#: cms/djangoapps/contentstore/views/course.py:645
msgid "Set Date"
msgstr ""

#: cms/djangoapps/contentstore/views/course.py:820
msgid ""
"Special characters not allowed in organization, course number, and course "
"run."
msgstr "組織、講座番号、course runでは特殊記号を使用することができません。"

#: cms/djangoapps/contentstore/views/course.py:856
msgid ""
"There is already a course defined with the same organization and course "
"number. Please change either organization or course number to be unique."
msgstr "既に同一の組織および講座番号で定義されている講座があります。組織または講座番号を変更してください。"

#: cms/djangoapps/contentstore/views/course.py:861
#: cms/djangoapps/contentstore/views/course.py:864
msgid ""
"Please change either the organization or course number so that it is unique."
msgstr "他と重複しないように、組織または講座番号を変更してください。"

#: cms/djangoapps/contentstore/views/course.py:869
#, python-brace-format
msgid ""
"Unable to create course '{name}'.\n"
"\n"
"{err}"
msgstr ""
"講座'{name}を作成できません。\n"
"\n"
"{err}"

#: cms/djangoapps/contentstore/views/course.py:882
msgid ""
"You must link this course to an organization in order to continue. "
"Organization you selected does not exist in the system, you will need to add"
" it to the system"
msgstr ""
"続けるためには、この講座を組織にリンクさせる必要があります。選択された組織はこのシステムに登録されていませんので、追加登録する必要があります。"

#: cms/djangoapps/contentstore/views/course.py:1168
msgid "Invalid prerequisite course key"
msgstr "無効な履習要件コースキー"

#: cms/djangoapps/contentstore/views/course.py:1373
msgid "An error occurred while trying to save your tabs"
msgstr "タブを保存する際にエラーが発生しました"

#: cms/djangoapps/contentstore/views/course.py:1374
msgid "Tabs Exception"
msgstr "タブの例外"

#: cms/djangoapps/contentstore/views/course.py:1601
msgid "This group configuration is in use and cannot be deleted."
msgstr "このグループ設定は利用中のため削除できません。"

#: cms/djangoapps/contentstore/views/course.py:1615
msgid "This content group is in use and cannot be deleted."
msgstr "このコンテンツグループは利用中のため削除できません。"

#: cms/djangoapps/contentstore/views/entrance_exam.py:159
msgid "Entrance Exam - Subsection"
msgstr "受講前試験 - サブセクション"

#: cms/djangoapps/contentstore/views/entrance_exam.py:253
msgid "Completed Course Entrance Exam"
msgstr "受講前試験終了"

#: cms/djangoapps/contentstore/views/export_git.py:48
msgid "Course successfully exported to git repository"
msgstr "gitレポジトリへのエクスポートが完了したコース"

#: cms/djangoapps/contentstore/views/helpers.py:135
msgid "Vertical"
msgstr "縦"

#: cms/djangoapps/contentstore/views/helpers.py:139
msgid "Section"
msgstr ""

#: cms/djangoapps/contentstore/views/helpers.py:141
msgid "Subsection"
msgstr ""

#: cms/djangoapps/contentstore/views/import_export.py:172
msgid "File upload corrupted. Please try again"
msgstr "ファイルアップロードが失敗しました。再度お試しください"

#: cms/djangoapps/contentstore/views/item.py:237
#: cms/djangoapps/contentstore/views/item.py:725
#, python-brace-format
msgid "Libraries cannot have more than {limit} components"
msgstr ""

#: cms/djangoapps/contentstore/views/item.py:625
msgid "Invalid data"
msgstr "無効なデータ"

#: cms/djangoapps/contentstore/views/item.py:627
#, python-brace-format
msgid "Invalid data ({details})"
msgstr "無効なデータ ({details})"

#: cms/djangoapps/contentstore/views/item.py:817
#, python-brace-format
msgid "You can not move {source_type} into {target_parent_type}."
msgstr "{source_type}を{target_parent_type}に移動できません。"

#: cms/djangoapps/contentstore/views/item.py:822
msgid "Item is already present in target location."
msgstr "ご希望のロケーションに既にアイテムがあります。"

#: cms/djangoapps/contentstore/views/item.py:824
msgid "You can not move an item into itself."
msgstr "アイテムを同じ場所には移動できません。"

#: cms/djangoapps/contentstore/views/item.py:826
msgid "You can not move an item into it's child."
msgstr "アイテムを子へ移動することはできません。"

#: cms/djangoapps/contentstore/views/item.py:828
msgid "You can not move an item directly into content experiment."
msgstr "コンテンツテストに直接アイテムを移動することはできません。"

#: cms/djangoapps/contentstore/views/item.py:830
#, python-brace-format
msgid "{source_usage_key} not found in {parent_usage_key}."
msgstr "{parent_usage_key}内に{source_usage_key}がありません。"

#: cms/djangoapps/contentstore/views/item.py:838
#, python-brace-format
msgid ""
"You can not move {source_usage_key} at an invalid index ({target_index})."
msgstr "無効な見出し({target_index})のため、{source_usage_key}は移動できません。"

#: cms/djangoapps/contentstore/views/item.py:843
#, python-brace-format
msgid "You must provide target_index ({target_index}) as an integer."
msgstr "target_index ({target_index}) は整数でなければいけません。"

#: cms/djangoapps/contentstore/views/item.py:902
#, python-brace-format
msgid "Duplicate of {0}"
msgstr "'{0}' の重複"

#: cms/djangoapps/contentstore/views/item.py:904
#, python-brace-format
msgid "Duplicate of '{0}'"
msgstr "'{0}' の重複"

#. Translators: The {pct_sign} here represents the percent sign, i.e., '%'
#. in many languages. This is used to avoid Transifex's misinterpreting of
#. '% o'. The percent sign is also translatable as a standalone string.
#: cms/djangoapps/contentstore/views/item.py:1204
#, python-brace-format
msgid ""
"Students must score {score}{pct_sign} or higher to access course materials."
msgstr "受講者が教材にアクセスするには {score}{pct_sign}以上の得点が必要です。"

#. Translators: This is the percent sign. It will be used to represent
#. a percent value out of 100, e.g. "58%" means "58/100".
#: cms/djangoapps/contentstore/views/item.py:1208
msgid "%"
msgstr "%"

#: cms/djangoapps/contentstore/views/item.py:1580
#, python-brace-format
msgid "{section_or_subsection} \"{display_name}\""
msgstr "{section_or_subsection} \"{display_name}\""

#: cms/djangoapps/contentstore/views/library.py:185
#, python-brace-format
msgid "Unable to create library - missing required field '{field}'"
msgstr "ライブラリを作成できません - '{field}'は必須"

#: cms/djangoapps/contentstore/views/library.py:190
#, python-brace-format
msgid ""
"Unable to create library '{name}'.\n"
"\n"
"{err}"
msgstr ""
"ライブラリ'{name}'を作成できません\n"
"\n"
"{err}"

#: cms/djangoapps/contentstore/views/library.py:196
msgid ""
"There is already a library defined with the same organization and library "
"code. Please change your library code so that it is unique within your "
"organization."
msgstr "既に同一の組織およびライブラリコードで定義されているライブラリがあります。組織内で重複しないようライブラリコードを変更してください。"

#: cms/djangoapps/contentstore/views/preview.py:288
#, python-brace-format
msgid "Access restricted to: {list_of_groups}"
msgstr "アクセス制限: {list_of_groups}"

#: cms/djangoapps/contentstore/views/transcript_settings.py:126
msgid "The information you entered is incorrect."
msgstr ""

#: cms/djangoapps/contentstore/views/transcripts_ajax.py:149
#: cms/djangoapps/contentstore/views/transcripts_ajax.py:469
msgid "Transcripts are supported only for \"video\" modules."
msgstr "字幕は\"動画\"モジュールのみ対応します。"

#: cms/djangoapps/contentstore/views/transcripts_ajax.py:151
msgid "Cannot find item by locator."
msgstr ""

#: cms/djangoapps/contentstore/views/transcripts_ajax.py:172
msgid "Video locator is required."
msgstr ""

#: cms/djangoapps/contentstore/views/transcripts_ajax.py:176
msgid "This transcript file type is not supported."
msgstr ""

#: cms/djangoapps/contentstore/views/transcripts_ajax.py:178
msgid "Video ID is required."
msgstr ""

#: cms/djangoapps/contentstore/views/transcripts_ajax.py:461
#: cms/djangoapps/contentstore/views/transcripts_ajax.py:503
msgid "Incoming video data is empty."
msgstr "入力された動画データは空です。"

#: cms/djangoapps/contentstore/views/transcripts_ajax.py:466
msgid "Can't find item by locator."
msgstr "ロケーターでアイテムを見つけることができません。"

#: cms/djangoapps/contentstore/views/transcripts_ajax.py:552
#: cms/djangoapps/contentstore/views/transcripts_ajax.py:591
msgid "No such transcript."
msgstr ""

#: cms/djangoapps/contentstore/views/transcripts_ajax.py:562
msgid "There is a problem with the chosen transcript file."
msgstr ""

#: cms/djangoapps/contentstore/views/transcripts_ajax.py:602
msgid ""
"There is a problem with the existing transcript file. Please upload a "
"different file."
msgstr ""

#: cms/djangoapps/contentstore/views/transcripts_ajax.py:622
msgid "YouTube ID is required."
msgstr ""

#: cms/djangoapps/contentstore/views/transcripts_ajax.py:639
msgid "There is a problem with the YouTube transcript file."
msgstr ""

#: cms/djangoapps/contentstore/views/user.py:108
msgid "Insufficient permissions"
msgstr "権限が不十分です"

#: cms/djangoapps/contentstore/views/user.py:120
#, python-brace-format
msgid "Could not find user by email address '{email}'."
msgstr "メールアドレス '{email}' でユーザーを見つけることができませんでした。"

#: cms/djangoapps/contentstore/views/user.py:159
msgid "No `role` specified."
msgstr "`role`が指定されていません。"

#: cms/djangoapps/contentstore/views/user.py:164
#, python-brace-format
msgid "User {email} has registered but has not yet activated his/her account."
msgstr "ユーザー{email}は登録済みですが、アカウントが有効化されていません。"

#: cms/djangoapps/contentstore/views/user.py:185
msgid "Invalid `role` specified."
msgstr "無効な`role`が指定されています。"

#: cms/djangoapps/contentstore/views/user.py:189
msgid "You may not remove the last Admin. Add another Admin first."
msgstr "一番最近の管理者を削除することができません。先に別の管理者を追加してください。"

#. Translators: This is the status of an active video upload
#: cms/djangoapps/contentstore/views/videos.py:148
msgid "Uploading"
msgstr "アップデート中"

#. Translators: This is the status for a video that the servers are currently
#. processing
#: cms/djangoapps/contentstore/views/videos.py:150
msgid "In Progress"
msgstr "進行中"

#. Translators: This is the status for a video that the servers have
#. successfully processed
#: cms/djangoapps/contentstore/views/videos.py:152
msgid "Ready"
msgstr "準備完了"

#. Translators: This is the status for a video that is uploaded completely
#: cms/djangoapps/contentstore/views/videos.py:154
msgid "Uploaded"
msgstr "アップロード完了"

#. Translators: This is the status for a video that the servers have failed to
#. process
#: cms/djangoapps/contentstore/views/videos.py:156
msgid "Failed"
msgstr "失敗"

#. Translators: This is the status for a video that is cancelled during upload
#. by user
#: cms/djangoapps/contentstore/views/videos.py:158
msgid "Cancelled"
msgstr "キャンセルされました"

#. Translators: This is the status for a video which has failed
#. due to being flagged as a duplicate by an external or internal CMS
#: cms/djangoapps/contentstore/views/videos.py:161
msgid "Failed Duplicate"
msgstr "複製に失敗しました"

#. Translators: This is the status for a video which has duplicate token for
#. youtube
#: cms/djangoapps/contentstore/views/videos.py:163
msgid "YouTube Duplicate"
msgstr "YouTube 複製"

#. Translators: This is the status for a video for which an invalid
#. processing token was provided in the course settings
#: cms/djangoapps/contentstore/views/videos.py:166
msgid "Invalid Token"
msgstr "無効なトークン"

#. Translators: This is the status for a video that was included in a course
#. import
#: cms/djangoapps/contentstore/views/videos.py:168
msgid "Imported"
msgstr "インポート完了"

#. Translators: This is the status for a video that is in an unknown state
#: cms/djangoapps/contentstore/views/videos.py:170
msgid "Unknown"
msgstr "不明"

#. Translators: This is the status for a video that is having its
#. transcription in progress on servers
#: cms/djangoapps/contentstore/views/videos.py:172
msgid "Transcription in Progress"
msgstr ""

#. Translators: This is the status for a video whose transcription is complete
#: cms/djangoapps/contentstore/views/videos.py:174
msgid "Transcript Ready"
msgstr ""

#. Translators: This is the status for a video whose transcription job was
#. failed for some languages
#: cms/djangoapps/contentstore/views/videos.py:176
msgid "Partial Failure"
msgstr ""

#. Translators: This is the status for a video whose transcription job has
#. failed altogether
#: cms/djangoapps/contentstore/views/videos.py:178
msgid "Transcript Failed"
msgstr ""

#: cms/djangoapps/contentstore/views/videos.py:263
msgid "An image file is required."
msgstr "画像ファイルは必須です。"

#. Translators: This is the header for a CSV file column
#. containing URLs for video encodings for the named profile
#. (e.g. desktop, mobile high quality, mobile low quality)
#: cms/djangoapps/contentstore/views/videos.py:422
#, python-brace-format
msgid "{profile_name} URL"
msgstr "{profile_name} URL"

#: cms/djangoapps/contentstore/views/videos.py:428
msgid "Duration"
msgstr "期間"

#: cms/djangoapps/contentstore/views/videos.py:429
msgid "Date Added"
msgstr "追加日"

#. Translators: This is the suggested filename when downloading the URL
#. listing for videos uploaded through Studio
#: cms/djangoapps/contentstore/views/videos.py:467
#, python-brace-format
msgid "{course}_video_urls"
msgstr "{course}_video_urls"

#: cms/djangoapps/contentstore/views/videos.py:901
msgid "A non zero positive integer is expected"
msgstr ""

#: cms/djangoapps/course_creators/models.py:38
msgid "unrequested"
msgstr "要求されていない"

#: cms/djangoapps/course_creators/models.py:39
msgid "pending"
msgstr "保留中"

#: cms/djangoapps/course_creators/models.py:40
msgid "granted"
msgstr "許可"

#: cms/djangoapps/course_creators/models.py:41
msgid "denied"
msgstr "拒否"

#: cms/djangoapps/course_creators/models.py:44
msgid "Studio user"
msgstr "Studioユーザー"

#: cms/djangoapps/course_creators/models.py:46
msgid "The date when state was last updated"
msgstr "状態の最新更新日時"

#: cms/djangoapps/course_creators/models.py:48
msgid "Current course creator state"
msgstr "現在の講座制作状況"

#: cms/djangoapps/course_creators/models.py:49
msgid ""
"Optional notes about this user (for example, why course creation access was "
"denied)"
msgstr "このユーザーへの補足説明 (例. 講座制作画面へのアクセス拒否理由)"

#: cms/djangoapps/maintenance/views.py:37
msgid "Force Publish Course"
msgstr "講座強制公開"

#: cms/djangoapps/maintenance/views.py:40
msgid ""
"Sometimes the draft and published branches of a course can get out of sync. "
"Force publish course command resets the published branch of a course to "
"point to the draft branch, effectively force publishing the course. This "
"view dry runs the force publish command"
msgstr ""
"ドラフトおよび公開済ブランチは時に同期から外れることができます。講座強制公開コマンドは公開中のブランチをドラフトブランチ時点にリセットし、効果的に強制公開します。このビューは強制公開コマンドをドライランします"

#: cms/djangoapps/maintenance/views.py:47
msgid "Edit Announcements"
msgstr ""

#: cms/djangoapps/maintenance/views.py:50
msgid ""
"This view shows the announcement editor to create or alter announcements "
"that are shown on the rightside of the dashboard."
msgstr ""

#: cms/djangoapps/maintenance/views.py:58
msgid "Please provide course id."
msgstr "講座IDを入力してください。"

#: cms/djangoapps/maintenance/views.py:59
msgid "Invalid course key."
msgstr "無効な講座キー。"

#: cms/djangoapps/maintenance/views.py:60
msgid "No matching course found."
msgstr "該当する講座が見つかりません。"

#: cms/djangoapps/maintenance/views.py:201
msgid "Force publishing course is not supported with old mongo courses."
msgstr "古いMongoの講座では、講座の強制公開はサポートされていません。"

#: cms/djangoapps/maintenance/views.py:215
msgid "Course is already in published state."
msgstr "講座はすでに公開済みの状態です。"

#: cms/djangoapps/models/settings/course_metadata.py:212
#, python-brace-format
msgid "Incorrect format for field '{name}'. {detailed_message}"
msgstr "'{name}'欄のフォーマットが正しくありません。 {detailed_message}"

#: cms/lib/xblock/tagging/tagging.py:25
msgid "Dictionary with the available tags"
msgstr "利用可能なタグのディクショナリ"

#: cms/urls.py:24
msgid "Studio Administration"
msgstr ""
